name: tutorial1
on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        user: actions/setup-python@v4
        with: 
          python-version:3.9
        
  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: step2
        run: echo " hello from job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: step 3
        run: echo "hello from job 3"
 
  job4:
    runs-on: ubuntu-latest
    steps:
      - name: step 4
        run: echo "I am job 4"
